export const regions = [
  { id: 1, name: 'Germany' },
  { id: 2, name: 'France' },
  { id: 3, name: 'Italy' },
  { id: 4, name: 'Spain' },
  { id: 5, name: 'United Kingdom' },
  { id: 6, name: 'United States' },
  { id: 7, name: 'China' },
  { id: 8, name: 'Japan' },
  { id: 9, name: 'South Korea' },
  { id: 10, name: 'Brazil' },
  { id: 11, name: 'India' },
  { id: 12, name: 'Russia' },
  { id: 13, name: 'Canada' },
  { id: 14, name: 'Australia' },
  { id: 15, name: 'Netherlands' },
  { id: 16, name: 'Singapore' },
  { id: 17, name: 'Hong Kong SAR, China' },
  { id: 18, name: 'Switzerland' },
  { id: 19, name: 'Thailand' },
  { id: 20, name: 'Viet Nam' },
  { id: 21, name: 'Taiwan, China' },
  { id: 22, name: 'Slovenia' },
  { id: 23, name: 'Republic of Ireland' },
  { id: 24, name: 'Romania' },
  { id: 25, name: 'Belgium' },
  { id: 26, name: 'Malaysia' },
  { id: 27, name: 'Kuwait' },
  { id: 28, name: 'South Africa' },
  { id: 29, name: 'Indonesia' },
  { id: 30, name: 'Philippines' },
  { id: 31, name: 'Sweden' },
  { id: 32, name: 'Mongolia' },
  { id: 33, name: 'Bulgaria' },
  { id: 34, name: 'Republic of Korea' },
  { id: 35, name: 'Macao SAR, China' },
  { id: 36, name: 'Poland' },
  { id: 37, name: 'New Zealand' },
  { id: 38, name: 'Colombia' },
  { id: 39, name: 'Finland' },
  { id: 40, name: 'Afghanistan' },
  { id: 41, name: 'Albania' },
  { id: 42, name: 'Algeria' },
  { id: 43, name: 'Andorra' },
  { id: 44, name: 'Angola' },
  { id: 45, name: 'Anguilla' },
  { id: 46, name: 'Antigua And Barbuda' },
  { id: 47, name: 'Argentina' },
  { id: 48, name: 'Armenia' },
  { id: 49, name: 'Aruba' },
  { id: 50, name: 'Austria' },
  { id: 51, name: 'Azerbaijan' },
  { id: 52, name: 'Bahamas' },
  { id: 53, name: 'Bahrain' },
  { id: 54, name: 'Bangladesh' },
  { id: 55, name: 'Barbados' },
  { id: 56, name: 'Belarus' },
  { id: 57, name: 'Belize' },
  { id: 58, name: 'Benin' },
  { id: 59, name: 'Bermuda' },
  { id: 60, name: 'Bhutan' },
  { id: 61, name: 'Bolivia' },
  { id: 62, name: 'Bosnia And Herzegovina' },
  { id: 63, name: 'Botswana' },
  { id: 64, name: 'British Virgin Islands' },
  { id: 65, name: 'Brunei Darussalam' },
  { id: 66, name: 'Burkina Faso' },
  { id: 67, name: 'Burundi' },
  { id: 68, name: 'Cabo Verde' },
  { id: 69, name: 'Cambodia' },
  { id: 70, name: 'Cameroon' },
  { id: 71, name: 'Caribbean Netherlands' },
  { id: 72, name: 'Cayman Islands' },
  { id: 73, name: 'Central African Republic' },
  { id: 74, name: 'Chad' },
  { id: 75, name: 'Channel Islands' },
  { id: 76, name: 'Chile' },
  { id: 77, name: 'China Hong Kong Sar' },
  { id: 78, name: 'China Macao Sar' },
  { id: 79, name: 'Comoros' },
  { id: 80, name: 'Congo' },
  { id: 81, name: 'Cook Islands' },
  { id: 82, name: 'Costa Rica' },
  { id: 83, name: 'Cote D Ivoire' },
  { id: 84, name: 'Croatia' },
  { id: 85, name: 'Cuba' },
  { id: 86, name: 'Curacao' },
  { id: 87, name: 'Cyprus' },
  { id: 88, name: 'Czech Republic' },
  { id: 89, name: 'Democratic Republic Of The Congo' },
  { id: 90, name: 'Denmark' },
  { id: 91, name: 'Djibouti' },
  { id: 92, name: 'Dominica' },
  { id: 93, name: 'Dominican Republic' },
  { id: 94, name: 'Ecuador' },
  { id: 95, name: 'Egypt' },
  { id: 96, name: 'El Salvador' },
  { id: 97, name: 'Equatorial Guinea' },
  { id: 98, name: 'Eritrea' },
  { id: 99, name: 'Estonia' },
  { id: 100, name: 'Ethiopia' },
  { id: 101, name: 'Faeroe Islands' },
  { id: 102, name: 'Falkland Islands Malvinas' },
  { id: 103, name: 'Fiji' },
  { id: 104, name: 'French Guiana' },
  { id: 105, name: 'French Polynesia' },
  { id: 106, name: 'Gabon' },
  { id: 107, name: 'Gambia' },
  { id: 108, name: 'Georgia' },
  { id: 109, name: 'Ghana' },
  { id: 110, name: 'Gibraltar' },
  { id: 111, name: 'Greece' },
  { id: 112, name: 'Greenland' },
  { id: 113, name: 'Grenada' },
  { id: 114, name: 'Guadeloupe' },
  { id: 115, name: 'Guatemala' },
  { id: 116, name: 'Guinea Bissau' },
  { id: 117, name: 'Guinea' },
  { id: 118, name: 'Guyana' },
  { id: 119, name: 'Haiti' },
  { id: 120, name: 'Holy See' },
  { id: 121, name: 'Honduras' },
  { id: 122, name: 'Hungary' },
  { id: 123, name: 'Iceland' },
  { id: 124, name: 'Iran' },
  { id: 125, name: 'Iraq' },
  { id: 126, name: 'Ireland' },
  { id: 127, name: 'Isle Of Man' },
  { id: 128, name: 'Israel' },
  { id: 129, name: 'Jamaica' },
  { id: 130, name: 'Jordan' },
  { id: 131, name: 'Kazakhstan' },
  { id: 132, name: 'Kenya' },
  { id: 133, name: 'Kiribati' },
  { id: 134, name: 'Kyrgyzstan' },
  { id: 135, name: 'Laos' },
  { id: 136, name: 'Latvia' },
  { id: 137, name: 'Lebanon' },
  { id: 138, name: 'Lesotho' },
  { id: 139, name: 'Liberia' },
  { id: 140, name: 'Libya' },
  { id: 141, name: 'Liechtenstein' },
  { id: 142, name: 'Lithuania' },
  { id: 143, name: 'Luxembourg' },
  { id: 144, name: 'Macedonia' },
  { id: 145, name: 'Madagascar' },
  { id: 146, name: 'Malawi' },
  { id: 147, name: 'Maldives' },
  { id: 148, name: 'Mali' },
  { id: 149, name: 'Malta' },
  { id: 150, name: 'Marshall Islands' },
  { id: 151, name: 'Martinique' },
  { id: 152, name: 'Mauritania' },
  { id: 153, name: 'Mauritius' },
  { id: 154, name: 'Mayotte' },
  { id: 155, name: 'Mexico' },
  { id: 156, name: 'Micronesia' },
  { id: 157, name: 'Moldova' },
  { id: 158, name: 'Monaco' },
  { id: 159, name: 'Montenegro' },
  { id: 160, name: 'Montserrat' },
  { id: 161, name: 'Morocco' },
  { id: 162, name: 'Mozambique' },
  { id: 163, name: 'Myanmar' },
  { id: 164, name: 'Namibia' },
  { id: 165, name: 'Nauru' },
  { id: 166, name: 'Nepal' },
  { id: 167, name: 'New Caledonia' },
  { id: 168, name: 'Nicaragua' },
  { id: 169, name: 'Niger' },
  { id: 170, name: 'Nigeria' },
  { id: 171, name: 'Niue' },
  { id: 172, name: 'Norway' },
  { id: 173, name: 'Oman' },
  { id: 174, name: 'Pakistan' },
  { id: 175, name: 'Palau' },
  { id: 176, name: 'Panama' },
  { id: 177, name: 'Papua New Guinea' },
  { id: 178, name: 'Paraguay' },
  { id: 179, name: 'Peru' },
  { id: 180, name: 'Portugal' },
  { id: 181, name: 'Qatar' },
  { id: 182, name: 'Reunion' },
  { id: 183, name: 'Russia' },
  { id: 184, name: 'Rwanda' },
  { id: 185, name: 'Saint Barthelemy' },
  { id: 186, name: 'Saint Helena' },
  { id: 187, name: 'Saint Kitts And Nevis' },
  { id: 188, name: 'Saint Lucia' },
  { id: 189, name: 'Saint Martin' },
  { id: 190, name: 'Saint Pierre And Miquelon' },
  { id: 191, name: 'Saint Vincent And The Grenadines' },
  { id: 192, name: 'Samoa' },
  { id: 193, name: 'San Marino' },
  { id: 194, name: 'Sao Tome And Principe' },
  { id: 195, name: 'Saudi Arabia' },
  { id: 196, name: 'Senegal' },
  { id: 197, name: 'Serbia' },
  { id: 198, name: 'Seychelles' },
  { id: 199, name: 'Sierra Leone' },
  { id: 200, name: 'Sint Maarten' },
]

// Région par défaut (France)
export const defaultRegion = regions[2]
